# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm@10.9.0

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running user scripts, then run build scripts explicitly
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy rest of the sources
COPY . .

# Build the project
RUN pnpm run build

# Expose nothing (stdio)

# Default command
CMD ["node", "dist/index.js"]
