name: Sync to GitHub

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'kaiyuanxiaobing'
          git config --global user.email 'kaiyuanxiaobing@foxmail.com'

      - name: Add remote GitHub repository
        run: git remote add github https://github.com/kaiyuanxiaobing/atomgit-mcp-server.git

      - name: Pull from GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_KEY }}
        run: |
          git remote set-url github https://x-access-token:${GITHUB_TOKEN}@github.com/kaiyuanxiaobing/atomgit-mcp-server.git
          git config pull.rebase false
          git pull github master --allow-unrelated-histories
          
      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_KEY }}
        run: |
          git remote set-url github https://x-access-token:${GITHUB_TOKEN}@github.com/kaiyuanxiaobing/atomgit-mcp-server.git
          git push github master
