name: Sync to GitHub

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'kaiyuanxiaobing'
          git config --global user.email 'kaiyuanxiaobing@foxmail.com'
        
      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_KEY }}
        run: |
          git remote add github https://${GITHUB_TOKEN}@github.com/kaiyuanxiaobing/atomgit-mcp-server.git
          git branch -M master
          git push github master
