name: Sync to GitHub

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git
        run: |
          git config --global user.name 'kaiyuanxiaobing'
          git config --global user.email 'kaiyuanxiaobing@foxmail.com'
        
      - name: Push to GitHub
        run: |
          echo "The secret is ${{ secrets.GIT_KEY }}"
          git remote add github https://${{ secrets.GIT_KEY }}@github.com/kaiyuanxiaobing/atomgit-mcp-server.git
          git branch -M master
          git push -u github master
